// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/psyb0t/elelem"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDriver creates a new instance of MockDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDriver {
	mock := &MockDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDriver is an autogenerated mock type for the Driver type
type MockDriver struct {
	mock.Mock
}

type MockDriver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDriver) EXPECT() *MockDriver_Expecter {
	return &MockDriver_Expecter{mock: &_m.Mock}
}

// Capabilities provides a mock function for the type MockDriver
func (_mock *MockDriver) Capabilities(model elelem.Model) elelem.Capabilities {
	ret := _mock.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for Capabilities")
	}

	var r0 elelem.Capabilities
	if returnFunc, ok := ret.Get(0).(func(elelem.Model) elelem.Capabilities); ok {
		r0 = returnFunc(model)
	} else {
		r0 = ret.Get(0).(elelem.Capabilities)
	}
	return r0
}

// MockDriver_Capabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capabilities'
type MockDriver_Capabilities_Call struct {
	*mock.Call
}

// Capabilities is a helper method to define mock.On call
//   - model elelem.Model
func (_e *MockDriver_Expecter) Capabilities(model interface{}) *MockDriver_Capabilities_Call {
	return &MockDriver_Capabilities_Call{Call: _e.mock.On("Capabilities", model)}
}

func (_c *MockDriver_Capabilities_Call) Run(run func(model elelem.Model)) *MockDriver_Capabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 elelem.Model
		if args[0] != nil {
			arg0 = args[0].(elelem.Model)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDriver_Capabilities_Call) Return(capabilities elelem.Capabilities) *MockDriver_Capabilities_Call {
	_c.Call.Return(capabilities)
	return _c
}

func (_c *MockDriver_Capabilities_Call) RunAndReturn(run func(model elelem.Model) elelem.Capabilities) *MockDriver_Capabilities_Call {
	_c.Call.Return(run)
	return _c
}

// Complete provides a mock function for the type MockDriver
func (_mock *MockDriver) Complete(context1 context.Context, driverRequest elelem.DriverRequest, fn func(elelem.Delta) error) (elelem.Usage, error) {
	ret := _mock.Called(context1, driverRequest, fn)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 elelem.Usage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, elelem.DriverRequest, func(elelem.Delta) error) (elelem.Usage, error)); ok {
		return returnFunc(context1, driverRequest, fn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, elelem.DriverRequest, func(elelem.Delta) error) elelem.Usage); ok {
		r0 = returnFunc(context1, driverRequest, fn)
	} else {
		r0 = ret.Get(0).(elelem.Usage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, elelem.DriverRequest, func(elelem.Delta) error) error); ok {
		r1 = returnFunc(context1, driverRequest, fn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockDriver_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - context1 context.Context
//   - driverRequest elelem.DriverRequest
//   - fn func(elelem.Delta) error
func (_e *MockDriver_Expecter) Complete(context1 interface{}, driverRequest interface{}, fn interface{}) *MockDriver_Complete_Call {
	return &MockDriver_Complete_Call{Call: _e.mock.On("Complete", context1, driverRequest, fn)}
}

func (_c *MockDriver_Complete_Call) Run(run func(context1 context.Context, driverRequest elelem.DriverRequest, fn func(elelem.Delta) error)) *MockDriver_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 elelem.DriverRequest
		if args[1] != nil {
			arg1 = args[1].(elelem.DriverRequest)
		}
		var arg2 func(elelem.Delta) error
		if args[2] != nil {
			arg2 = args[2].(func(elelem.Delta) error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDriver_Complete_Call) Return(usage elelem.Usage, err error) *MockDriver_Complete_Call {
	_c.Call.Return(usage, err)
	return _c
}

func (_c *MockDriver_Complete_Call) RunAndReturn(run func(context1 context.Context, driverRequest elelem.DriverRequest, fn func(elelem.Delta) error) (elelem.Usage, error)) *MockDriver_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// ListModels provides a mock function for the type MockDriver
func (_mock *MockDriver) ListModels(context1 context.Context) ([]string, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListModels")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_ListModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListModels'
type MockDriver_ListModels_Call struct {
	*mock.Call
}

// ListModels is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockDriver_Expecter) ListModels(context1 interface{}) *MockDriver_ListModels_Call {
	return &MockDriver_ListModels_Call{Call: _e.mock.On("ListModels", context1)}
}

func (_c *MockDriver_ListModels_Call) Run(run func(context1 context.Context)) *MockDriver_ListModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDriver_ListModels_Call) Return(strings []string, err error) *MockDriver_ListModels_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockDriver_ListModels_Call) RunAndReturn(run func(context1 context.Context) ([]string, error)) *MockDriver_ListModels_Call {
	_c.Call.Return(run)
	return _c
}

// Stream provides a mock function for the type MockDriver
func (_mock *MockDriver) Stream(context1 context.Context, driverRequest elelem.DriverRequest, fn func(elelem.Delta) error) (elelem.Usage, error) {
	ret := _mock.Called(context1, driverRequest, fn)

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 elelem.Usage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, elelem.DriverRequest, func(elelem.Delta) error) (elelem.Usage, error)); ok {
		return returnFunc(context1, driverRequest, fn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, elelem.DriverRequest, func(elelem.Delta) error) elelem.Usage); ok {
		r0 = returnFunc(context1, driverRequest, fn)
	} else {
		r0 = ret.Get(0).(elelem.Usage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, elelem.DriverRequest, func(elelem.Delta) error) error); ok {
		r1 = returnFunc(context1, driverRequest, fn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Stream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stream'
type MockDriver_Stream_Call struct {
	*mock.Call
}

// Stream is a helper method to define mock.On call
//   - context1 context.Context
//   - driverRequest elelem.DriverRequest
//   - fn func(elelem.Delta) error
func (_e *MockDriver_Expecter) Stream(context1 interface{}, driverRequest interface{}, fn interface{}) *MockDriver_Stream_Call {
	return &MockDriver_Stream_Call{Call: _e.mock.On("Stream", context1, driverRequest, fn)}
}

func (_c *MockDriver_Stream_Call) Run(run func(context1 context.Context, driverRequest elelem.DriverRequest, fn func(elelem.Delta) error)) *MockDriver_Stream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 elelem.DriverRequest
		if args[1] != nil {
			arg1 = args[1].(elelem.DriverRequest)
		}
		var arg2 func(elelem.Delta) error
		if args[2] != nil {
			arg2 = args[2].(func(elelem.Delta) error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDriver_Stream_Call) Return(usage elelem.Usage, err error) *MockDriver_Stream_Call {
	_c.Call.Return(usage, err)
	return _c
}

func (_c *MockDriver_Stream_Call) RunAndReturn(run func(context1 context.Context, driverRequest elelem.DriverRequest, fn func(elelem.Delta) error) (elelem.Usage, error)) *MockDriver_Stream_Call {
	_c.Call.Return(run)
	return _c
}

// TokenCounter provides a mock function for the type MockDriver
func (_mock *MockDriver) TokenCounter() elelem.TokenCounter {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TokenCounter")
	}

	var r0 elelem.TokenCounter
	if returnFunc, ok := ret.Get(0).(func() elelem.TokenCounter); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(elelem.TokenCounter)
		}
	}
	return r0
}

// MockDriver_TokenCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenCounter'
type MockDriver_TokenCounter_Call struct {
	*mock.Call
}

// TokenCounter is a helper method to define mock.On call
func (_e *MockDriver_Expecter) TokenCounter() *MockDriver_TokenCounter_Call {
	return &MockDriver_TokenCounter_Call{Call: _e.mock.On("TokenCounter")}
}

func (_c *MockDriver_TokenCounter_Call) Run(run func()) *MockDriver_TokenCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDriver_TokenCounter_Call) Return(tokenCounter elelem.TokenCounter) *MockDriver_TokenCounter_Call {
	_c.Call.Return(tokenCounter)
	return _c
}

func (_c *MockDriver_TokenCounter_Call) RunAndReturn(run func() elelem.TokenCounter) *MockDriver_TokenCounter_Call {
	_c.Call.Return(run)
	return _c
}
